### ISSUE TITLE
EspNowBroadcast do not work reliable

### ISSUE THREAD

**Issue by StefanL38** [yoursunny/WifiEspNow#14]
Hi yoursunny,

I tested your EspNowBroadcast.ino some more.

I pressed rest on two nodeMCU-boards to get ready for sending messages

```
20:48:50.164 -> MAC address of this node is EE:FA:BC:14:42:92
20:48:50.164 -> Press the button to send a message
20:49:33.499 -> Sending message
20:49:33.499 -> hello ESP-NOW from EE:FA:BC:14:42:92 at 43429
20:49:33.499 -> Recipients:
```

No recipient found even I can see both nodeMCUs with a wifi-monitor on my smartphone

After some additional button-presses on board 92 the other board responded

```
20:51:35.675 -> hello ESP-NOW from EE:FA:BC:14:42:92 at 165598
20:51:35.675 -> Recipients: 62:01:94:77:EC:FF
```

but then again not after some presses it responded but the other boardFF

did not show a message in the serial-monitor

after some presses sometimes it showed a message sometimes not

Same on the other side.

So both boards sometimes show a recipient sometime not

sometimes the receiving of a message was confirmed on the receiver sometimes not.

So i started varying your code instead of a while-loop that waits for the button to be unpressed 

I wrote a non-blocking variant with a flag and based on millis()  made no difference.

Then I started reading your library and discovered that the begin-function does have a third parameter which is not used in dem demo-sketch. So I set it to 1000 assuing the value is milliseconds.

made no difference too.

What I found really strange is the fact that my Smartphone-Wifi-scanner showed 

one nodeMCU was active on channel 3 the other was active on ch 13

then I tried different SSIDs on both devices. Then no recipients were found at all

Now I don't know what to do else to make it work reliable

best regards Stefan

**Comment by yoursunny** [comment]
The example specifies channel 3, but **Wifi Analyzer** app indicates `ESPNOW` APs are on channel 8, which is the same channel as my residential WiFi.
It turns out to be https://github.com/esp8266/Arduino/issues/2843 : I might have used these units to connect to my residential WiFi in the past without setting `WiFi.persistent(false)`, so that the firmware remembers "channel 8".
Since `WifiEspNowBroadcast.begin()` sets AP+STA mode, the channel for STA mode takes precedence, the firmware attempts to connect to the residential WiFi, and "channel 3" is ignored.

I have added `WiFi.disconnect()` and the channel is now correct.
However, a consequence is that, if user wishes to use ESP-NOW pseudo broadcast and WiFi STA mode at the same time, they must call `WifiEspNowBroadcast.begin()` before `WiFi.begin()`.
